2.1 Support, AWS Discovery, Generic C SDK Submodule, New IOTC C Lib, Flattened Dir Structure, Refactor
avnet-iotconnect/iotc-dialog-da16k-sdk pull request #17
Opened 2024-04-03 16:39 UTC by wtk-evoirin

- Parallelized build (= much faster build now)
- Generic C SDK as submodule (includes iotc-c-lib)
- Floating point printing enabled removing CJSON hacks
- Back to 1 build config due to new clib supporting both AWS and Azure
- AWS and Azure Discovery / Identity working now
- Added console CMD to set connection type
- Added AT CMD to set connection type
- Update usage listings
- Reworked and updated docs
- Removed requirement to set MQTT parameters manually
- Removed manual setting of CD
- Removed unused clutter from the repo
- Not shipping hacks in SDK files anymore
- Fixed problem of not being able to run setup and start client when there is no config at boot (i.e. after factory reset). So now you can configure and run the client immediately.

And probably a lot more I forgot about...

2024-04-05 14:35 UTC, pywtk approved these changes

2024-04-12 16:12 UTC, nik-markovic commented
Is there an actual value in checking in ".settings" from Eclipse at projects/da16200? I usually make sure that I .gitignore that directory.

2024-04-12 16:28 UTC, nik-markovic commented
If you use the approach you used in the setup.sh, then you lose the ability to track git changes in your development environment.
If you want to use the mechanism I used in https://github.com/avnet-iotconnect/iotc-azurertos-stm32-u5, then:
* I'd prefer you place the setup script in scripts/ directory from the root of the repo (also see "cd `dirname $0`/.." approach) and name it setup-project.sh  That way we have a uniform approach across all projects.
* In the repo first move all overrides into places that they would be to overlay on top of the project.
* Ask the user to download the Dialog-SDK zip to the root of the repo. Ask for a specific version to avoid any issues. You will use that specific version file name in the next steps.
* Explode Dialog-SDK-<version>.zip into a temporary directory
* cp -nr temporary_directory/* ../
* The step will ensure that original overlay files are not overwriten by whatever is in the SDK

2024-04-12 16:56 UTC, nik-markovic requested changes

2024-04-12 16:56 UTC, nik-markovic commented on doc/SETUP_APP.md
> +      It can be acquired here: https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem
Can we avoid the user providing certificates like we do in all other SDKs? Since we have to account for the DA use case for module not requiring a firmware update to update CA certificates, maybe we can somehow plug in "default" certificates and the give the user the option to provide updated ones.

This is maybe a TODO list for a future feature update maybe so we can limit the scope of this work.

2024-04-12 16:56 UTC, nik-markovic commented on doc/SETUP_APP.md
> +    It can be acquired here: https://www.amazontrust.com/repository/SFC2CA-SFSRootCAG2.pem
Should we be recommending the AmazonRootCA1? Laurent said that we should be using that one instead.

2024-04-12 16:56 UTC, nik-markovic commented on doc/SETUP_APP.md
> +* IoTConnect Environment **ENV**
Also in Key Vault

2024-04-12 16:56 UTC, nik-markovic commented
NWIC = Neil Witekio IoTConnect? :D

I think we should do a spearate forum eventually to discuss this AT command set concepts and commands thatr we may want to support for the future. 

Also if we consider the typical MQTT connect AT command as analogue, the whole connect is done in one shot - as in something like **AT+MQTTCONNECT profile,host,port,clientid,username,password* and it's all done. I feel the IoTConnect can do the same in the fashion like:
```
AT+IOTCCONNECT "aws","mydevid","mycpid","myenv",1(1=aws/2=azure),0(0=certs,1=sym_key)
```

Anyways, probably best done in a future pass with new feature, but throwing this out.

2024-04-12 17:36 UTC, nik-markovic requested changes

2024-04-12 17:36 UTC, nik-markovic commented on setup.sh
> +
Do ```set -e``` at the beginning so if anything fails along the way, we fail the script execution.

2024-04-12 17:36 UTC, nik-markovic commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_generic_sdk_da16k_mosquitto_client.c
> +/*
Should we add MIT license at the headings of our own code?

2024-04-12 17:36 UTC, nik-markovic commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_generic_sdk_da16k_mosquitto_client.c
> +    {
Several curly brace inconsistencies in this file and other files.

2024-04-12 17:36 UTC, nik-markovic commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_generic_sdk_da16k_mosquitto_client.c
> +//
I feel like there is too much spacing in all comments especially with the extra blank //

2024-04-12 17:36 UTC, nik-markovic commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_generic_sdk_da16k_mosquitto_client.c
> +#define HOST_URL_FORMAT "ssl://%s:8883"
Unused

2024-04-12 17:36 UTC, nik-markovic commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_app.c
> +TODO FIXME Reimplement for new iotc-c-lib
Doing it in this pass or the nex?

I guess also along with the comment *TODO FIXME CHECK Haven't set up any callbacks here*

The way this could work with AT commands is to send the asycnhronous events liek *IOTCCMD="my_command my_arg1 my_arg2" when a callback gets called.

Due to this reason, maybe we should consider having one SDK and two applications.
1. Sample application to run on the DA EVK board that would iteract with IoTConnect at application level, similar to our other samples.
2. Real application/service implementing our AT Command set, intended for interacting with other MCUs over UART.
... Just throwing this in as a thought.

2024-04-12 17:36 UTC, nik-markovic commented on apps/common/examples/Network/IoTConnect_Client/src/iotc-generic-c-sdk
I would still recommend using our own DA SDK. I know that we are using some of the logging, but looks more of a hack to include it all.

2024-04-12 17:36 UTC, nik-markovic commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_da16k_util.c
> +    c->env = NULL;
Slightly superficial: Looks like as if the user were to call this function twice, env, symmetric key etc may leak. Maybe detect if the user config has been cleared beforehand to avoid potential leaking? Basically fail if any value is not null.

2024-04-12 17:42 UTC, nik-markovic requested changes

2024-04-12 17:42 UTC, nik-markovic commented on apps/common/examples/Network/IoTConnect_Client/src/renesas_system/atcmd.c
atcmd_asynchony... < typo? "acynchronous? async?

Also still around "#if 1". Not sure if on purpose.

2024-04-12 17:45 UTC, nik-markovic requested changes

2024-04-12 17:45 UTC, nik-markovic commented on apps/da16200/get_started/src/apps/user_nvram_cmd_table.c
> +  { DA16X_CONF_STR_IOTCONNECT_CD,               "IOTC_CD", 64},
Do we need this CD value? I can't seem fo follow the trail, but we shouldn't need it if we are doing HTTP identity.

2024-04-16 10:18 UTC, wtk-evoirin commented on apps/common/examples/Network/IoTConnect_Client/src/renesas_system/atcmd.c
That's terminology used in the Renesas SDK which Neil adopted and I kept it :)

No, the #if 1 should be removed

2024-04-16 10:18 UTC, wtk-evoirin commented on apps/da16200/get_started/src/apps/user_nvram_cmd_table.c
> +  { DA16X_CONF_STR_IOTCONNECT_CD,               "IOTC_CD", 64},
No, will be removed

2024-04-18 10:24 UTC, oerg866 commented on doc/SETUP_APP.md
> +      It can be acquired here: https://cacerts.digicert.com/DigiCertGlobalRootG2.crt.pem
I agree. Will make a ticket for this.

2024-04-18 10:25 UTC, wtk-evoirin commented
> NWIC = Neil Witekio IoTConnect? :D
> 
> I think we should do a spearate forum eventually to discuss this AT command set concepts and commands thatr we may want to support for the future.
> 
> Also if we consider the typical MQTT connect AT command as analogue, the whole connect is done in one shot - as in something like *_AT+MQTTCONNECT profile,host,port,clientid,username,password_ and it's all done. I feel the IoTConnect can do the same in the fashion like:
> 
> ```
> AT+IOTCCONNECT "aws","mydevid","mycpid","myenv",1(1=aws/2=azure),0(0=certs,1=sym_key)
> ```
> 
> Anyways, probably best done in a future pass with new feature, but throwing this out.

I agree

2024-04-18 10:55 UTC, wtk-evoirin commented
> Is there an actual value in checking in ".settings" from Eclipse at projects/da16200? I usually make sure that I .gitignore that directory.

Removed

2024-04-19 17:00 UTC, wtk-evoirin commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_generic_sdk_da16k_mosquitto_client.c
> +/*
Done

2024-04-19 17:01 UTC, wtk-evoirin commented
> Is there an actual value in checking in ".settings" from Eclipse at projects/da16200? I usually make sure that I .gitignore that directory.



> If you use the approach you used in the setup.sh, then you lose the ability to track git changes in your development environment. If you want to use the mechanism I used in https://github.com/avnet-iotconnect/iotc-azurertos-stm32-u5, then:
> 
> * I'd prefer you place the setup script in scripts/ directory from the root of the repo (also see "cd `dirname $0`/.." approach) and name it setup-project.sh  That way we have a uniform approach across all projects.
> * In the repo first move all overrides into places that they would be to overlay on top of the project.
> * Ask the user to download the Dialog-SDK zip to the root of the repo. Ask for a specific version to avoid any issues. You will use that specific version file name in the next steps.
> * Explode Dialog-SDK-.zip into a temporary directory
> * cp -nr temporary_directory/* ../
> * The step will ensure that original overlay files are not overwriten by whatever is in the SDK



This is basically exactly how that script works, except it's in the root. I will put it in scripts/setup-project.sh

2024-04-19 18:39 UTC, nik-markovic approved these changes
Apporving the PR in order to progress to the final implementation and then we can re-review with these comments in mind.

2024-04-19 18:45 UTC, nik-markovic commented
> This is basically exactly how that script works, except it's in the root. I will put it in scripts/setup-project.sh
I must have been confused by something. These repos back and forth... :D

2024-04-25 13:04 UTC, merged