Command support
avnet-iotconnect/iotc-dialog-da16k-sdk pull request #18
Opened 2024-05-08 11:06 UTC by wtk-evoirin

2024-05-16 13:32 UTC, nik-markovic approved these changes

2024-05-16 13:32 UTC, nik-markovic commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_app.h
> +} iotc_command_queue_item_t;
Minor, Naming: iotc_command_queue_item_t should have camel case (per what our tpical project style does). Not sure if you are trying conform to the DA's project naming. If that's the case, then it's fine.

2024-05-16 19:43 UTC, nik-markovic requested changes

2024-05-21 07:58 UTC, wtk-evoirin commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_app.h
>  extern void stop_iotconnect(void);
Good point

2024-05-21 08:18 UTC, wtk-evoirin commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_app.c
> +    const char                  *ack_id         = iotcl_c2d_get_ack_id(data);
This has been addressed.

2024-05-21 08:19 UTC, wtk-evoirin commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_app.c
> +        if (pdTRUE == xQueueSendToBack(command_queue, &queue_entry, 0)) {
I have changed this.

2024-05-21 08:47 UTC, wtk-evoirin commented on apps/common/examples/Network/IoTConnect_Client/src/iotc_app/iotc_app.h
> +} iotc_command_queue_item_t;
Yes, this is to stay consistent with the DA. I have removed the _t suffix.

2024-05-22 14:11 UTC, nik-markovic approved these changes

2024-05-22 22:10 UTC, merged